#! /bin/sh
CH_AUTHOR_ZH="冯振华"
CH_AUTHOR_EN="Zhen-Hua Feng"
CH_EMAIL="fengzhenhua@mail.bnu.edu.cn"
CH_ORCID="0009-0000-2744-2368"
CH_CITY_ZH="北京"
CH_CITY_EN="Beijing"
CH_POSTCODE="100875"
CH_SCHOOL_ZH="北京师范大学"
CH_SCHOOL_EN="Beijing Normal University"
CH_INSTITUTE_ZH="物理与天文学院"
CH_INSTITUTE_EN="School of Physics and Astronomy"
CH_AFFILIATION_EN="$CH_INSTITUTE_EN , $CH_SCHOOL_EN, $CH_CITY_EN $CH_POSTCODE, $CH_CITY_EN"
